name: Go Compilation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'

    - name: Build
      run: go build ./...

    - name: Test
      run: go test -v ./...
      
    - name: Set status
      uses: github/set-status-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        state: ${{ job.status }}
        context: Go Compilation
        description: ${{ job.status }}
